# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := random
DEFS_Debug := '-DDEBUG'

# Flags passed to all source files.
CFLAGS_Debug := 

# Flags passed to only C files.
CFLAGS_C_Debug := 

# Flags passed to only C++ files.
CFLAGS_CC_Debug := 

INCS_Debug := -Imodules/random/include

DEFS_Release := '-DNDEBUG'

# Flags passed to all source files.
CFLAGS_Release := 

# Flags passed to only C files.
CFLAGS_C_Release := 

# Flags passed to only C++ files.
CFLAGS_CC_Release := 

INCS_Release := -Imodules/random/include

OBJS := $(obj).target/$(TARGET)/modules/random/random.o

# Add to the list of files we specially track dependencies for.
all_deps += $(OBJS)

# CFLAGS et al overrides must be target-local.
# See "Target-specific Variable Values" in the GNU Make manual.
$(OBJS): TOOLSET := $(TOOLSET)
$(OBJS): GYP_CFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE)) $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_C_$(BUILDTYPE))
$(OBJS): GYP_CXXFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE)) $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_CC_$(BUILDTYPE))

# Suffix rules, putting all outputs into $(obj).

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(srcdir)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# Try building from generated source, too.

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj).$(TOOLSET)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# End of this set of suffix rules
### Rules for final target.
LDFLAGS_Debug := 

LDFLAGS_Release := 

LIBS := 

$(obj).target/modules/random/librandom.so: GYP_LDFLAGS := $(LDFLAGS_$(BUILDTYPE))
$(obj).target/modules/random/librandom.so: LIBS := $(LIBS)
$(obj).target/modules/random/librandom.so: LD_INPUTS := $(OBJS)
$(obj).target/modules/random/librandom.so: TOOLSET := $(TOOLSET)
$(obj).target/modules/random/librandom.so: $(OBJS) FORCE_DO_CMD
	$(call do_cmd,solink)

all_deps += $(obj).target/modules/random/librandom.so
# Add target alias
.PHONY: random
random: $(builddir)/lib.target/librandom.so

# Copy this to the shared library output path.
$(builddir)/lib.target/librandom.so: TOOLSET := $(TOOLSET)
$(builddir)/lib.target/librandom.so: $(obj).target/modules/random/librandom.so FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(builddir)/lib.target/librandom.so
# Short alias for building this shared library.
.PHONY: librandom.so
librandom.so: $(obj).target/modules/random/librandom.so $(builddir)/lib.target/librandom.so

# Add shared library to "all" target.
.PHONY: all
all: $(builddir)/lib.target/librandom.so

