#!/bin/sh
#
#    00-header - create the header of the MOTD
#    Copyright (C) 2009-2010 Canonical Ltd.
#
#    Authors: Dustin Kirkland <kirkland@canonical.com>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License along
#    with this program; if not, write to the Free Software Foundation, Inc.,
#    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

color_end_mark="\033[0m"
logo_color="\033[32m\033[1m"
welcome_word_color="\033[36m"
disk_usage_color="\033[31m\033[4m"

echo ""
echo "$logo_color                 _ __ ___    _ __ ___     ______     __ _ __         $color_end_mark"
echo "$logo_color                |  _   _ \  |  _   _ \   /  _ _ \   /  _ _ _\          $color_end_mark "
echo "$logo_color                | | | | | | | | | | | |  | |___| | |  /                        $color_end_mark                         "
echo "$logo_color                | | | | | | | | | | | |  |  _____| |  |                $color_end_mark                                 "
echo "$logo_color                |_| |_| |_| |_| |_| |_|  | |       |  \__ _ _                  $color_end_mark "
echo "$logo_color                                         |_|        \ __ _ _/                          $color_end_mark"

echo "$welcome_word_color\nWelcome To MMPC Sdk Build Server!!!\n$color_end_mark"  

echo "${disk_usage_color}Disk Usage:$color_end_mark"
df -h | head -2
echo ""
