#!/bin/bash
#Copyright (C) 2010-2020 PScript Project
#Author:pengjun
#Email:peter517@126.com
#CreateTime:2014-08-28_18:01:40
#Comments: record every user operator history, add the content to end of /etc/profile
#

USER_HOSTNAME=`who -u am i 2>/dev/null| awk '{print $NF}'|sed -e 's/[()]//g'`
if [ "$USER_HOSTNAME" = "" ]
then
        USER_HOSTNAME=`hostname`
fi

path="//tmp//history"

if [ ! -d ${path} ]
then
        mkdir ${path}
        chmod 777 ${path}
fi

if [ ! -d ${path}/${LOGNAME} ]
then
        mkdir ${path}/${LOGNAME}
        chmod 300 ${path}/${LOGNAME}
fi

login_date=`date +%Y%m%d-%H%M%S`
export HISTSIZE=4096
export HISTFILE="${path}/${LOGNAME}/${login_date}.${USER_HOSTNAME}.dbhist"
export PROMPT_COMMAND="history -a; history -c; history -r; $PROMPT_COMMAND"
export HISTTIMEFORMAT='%F %T '

chmod 600 ${path}/${LOGNAME}/*dbhist* 2>/dev/null

