# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := linux_c_test
DEFS_Default := '-DGYP_DEFINE' \
	'-DIS_DEBUG'

# Flags passed to all source files.
CFLAGS_Default := -Werror \
	-Wall

# Flags passed to only C files.
CFLAGS_C_Default := 

# Flags passed to only C++ files.
CFLAGS_CC_Default := 

INCS_Default := -Imodules

OBJS := $(obj).target/$(TARGET)/main.o \
	$(obj).target/$(TARGET)/modules/pthread/pthread_once_test.o

# Add to the list of files we specially track dependencies for.
all_deps += $(OBJS)

# CFLAGS et al overrides must be target-local.
# See "Target-specific Variable Values" in the GNU Make manual.
$(OBJS): TOOLSET := $(TOOLSET)
$(OBJS): GYP_CFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_C_$(BUILDTYPE))
$(OBJS): GYP_CXXFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_CC_$(BUILDTYPE))

# Suffix rules, putting all outputs into $(obj).

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(srcdir)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# Try building from generated source, too.

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj).$(TOOLSET)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# End of this set of suffix rules
### Rules for final target.
LDFLAGS_Default := -pthread

LIBS := 

$(builddir)/linux_c_test: GYP_LDFLAGS := $(LDFLAGS_$(BUILDTYPE))
$(builddir)/linux_c_test: LIBS := $(LIBS)
$(builddir)/linux_c_test: LD_INPUTS := $(OBJS)
$(builddir)/linux_c_test: TOOLSET := $(TOOLSET)
$(builddir)/linux_c_test: $(OBJS) FORCE_DO_CMD
	$(call do_cmd,link)

all_deps += $(builddir)/linux_c_test
# Add target alias
.PHONY: linux_c_test
linux_c_test: $(builddir)/linux_c_test

# Add executable to "all" target.
.PHONY: all
all: $(builddir)/linux_c_test

